<!-- application/layouts/scripts/layout.phtml -->

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
  <meta charset="utf-8"/>
  <meta content="width=device-width; initial-scale=1.0;" name="viewport"/>
  <meta content="gbLDbh-Q1KfBG2HlZvIUsuGLsaHEXnO_kW30uedj-nU" name="google-site-verification"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
         
  <title>Visit Registration Form | Texas A&amp;M University, College Station, TX</title>
  <meta content="Visit Registration Form| Texas A&amp;M University, College Station, TX" name="title"/>
  <meta content="Texas A&amp;M University - Marketing &amp; Communications" name="author"/>
  <meta content="texas a&amp;m university, texas, a&amp;m, texas a&amp;m, aggies, texas aggies, 
    university, universities, college, colleges, higher education, college station, 12th man, visit,
    tour, registration" name="keywords"/>
  <meta content="Exploring campus for a short time or a lifetime, visitors to Texas A&amp;M 
    University soon learn why it's known as one of the friendliest campuses in the world, though it's one of 
    the largest in the United States." name="description"/>
         
  <meta content="Visit Registration Form | Texas A&amp;M University, College Station, TX" name="DC.Title"/>
  <meta content="Texas A&amp;M University - Marketing &amp; Communications" name="Author"/>
  <meta content="texas a&amp;m university, texas, a&amp;m, texas a&amp;m, aggies, texas aggies, 
    university, universities, college, colleges, higher education, college station, 12th man, visit,
    tour, registration" name="DC.Subject.Keyword"/>
  <meta content="Exploring campus for a short time or a lifetime, visitors to Texas A&amp;M 
    University soon learn why it's known as one of the friendliest campuses in the world, though it's one of 
    the largest in the United States." name="DC.Description"/>
         
  <link href="http://dmc-assets.tamu.edu/global/images/icons/favicon.ico" rel="shortcut icon"/>
  <link href="http://dmc-assets.tamu.edu/global/images/icons/apple-touch-icon.png" rel="apple-touch-icon"/>
  <link href="/css/defaults.css" rel="stylesheet"/>
  <link href="/css/styles.css" rel="stylesheet"/>
  <?php echo $this->headLink(); ?>
         
  <script src="http://dmc-assets.tamu.edu/global/javascript/modernizr-2.0.6.min.js"></script>
  <script src="http://dmc-assets.tamu.edu/global/javascript/jquery.min.js"></script>
  <script>
    var _gaq = _gaq || [];
        _gaq.push(
       ['_setAccount', 'UA-1617721-2'],
       ['_setDomainName', '.tamu.edu'],
       ['_trackPageview']
       );
 
       (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = 'http://dmc-assets.tamu.edu/global/javascript/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();
  </script>  
  <?php echo $this->headScript(); ?>

  <?php echo $this->JQuery(); ?>
</head>

<!--[if lt IE 7]> <body class="ie6 oldie"> <![endif]-->
<!--[if IE 7]>    <body class="ie7 oldie"> <![endif]-->
<!--[if IE 8]>    <body class="ie8 oldie"> <![endif]-->
<!--[if gt IE 8]><!--> <body> <!--<![endif]-->

<div id="wrapper"><a class="offPage" href="#container">skip to main content</a>
   <header>
   <div id="headerWrapper">
    <div id="rightHead">
    
    <form action="http://search.tamu.edu/search" id="searchForm" method="get"> 
      <label class="offPage" for="search_text_box">Search:</label> 
      <input id="search_text_box" maxlength="256" name="q" placeholder="  Visitor Search" type="search"/>
      <input id="search_button" type="submit" value=""/>
      <input name="output" type="hidden" value="xml_no_dtd"/> 
      <input name="site" type="hidden" value="visitor_collection"/> 
      <input name="client" type="hidden" value="TAMU_frontend"/> 
      <input name="proxystylesheet" type="hidden" value="TAMU_frontend"/> 
    </form>

    </div> <!--end rightHead-->
    <div id="logo"><a href="http://www.tamu.edu/"><span class="offPage">Texas A&amp;M Home</span></a></div>
       
    </div> <!--end headerWrapper-->     
  </header>

  <article id="secondary">
    <nav class="nav-collapse" id="primaryNavigation" role="navigation">      
      <ul id="primaryNav">
        <li><a href="/">Home</a></li>
        <li><a href="http://visit.tamu.edu/about/index.html">About A&amp;M</a></li>
        <li><a href="http://visit.tamu.edu/plan/index.html">Plan Your Visit</a></li>
        <li><a href="http://visit.tamu.edu/local/index.html">Local Community</a></li>
        <li><a href="http://visit.tamu.edu/visitor-center/index.html">Visitor Center</a></li>
        <li><a href="http://campustours.tamu.edu/">Virtual Tours</a></li>
      </ul>
    </nav>

    <h1 class="pageTitle">Campus Visit Registration</h1>
    <div id="container">
      <div class="spacer"></div> 
      <div id="mainContent">

<!-- ================================================================================================= -->


  <?php echo $this->layout()->content ?>


<!-- ================================================================================================= -->

      </div> <!-- end mainContent -->
      <div class="spacer"></div> 
    </div> <!--end container-->

    <footer>
    <div id="footerWrapper">
      <a href="http://www.tamu.edu/" id="tamLogo"><img alt="Texas A&amp;M Logo" 
        src="http://dmc-assets.tamu.edu/visit/images/footer_logo.png"/></a>
      <div id="findUs">
        <h2>Find Us</h2>
        <div class="item">
            <div class="itemname">Address:</div>
          <div class="itemvalue">   Texas A&amp;M University<br/>College Station, TX<br/> 77843-1372</div>
        </div>
        <div class="spacer"></div>    

        <div class="item">                 
          <div class="itemname">GPS:</div>
          <div class="itemvalue">30.613181, -96.339878</div>
        </div>
        <div class="spacer"></div>
 
        <div class="item">    
          <div class="itemname">Telephone:</div>
          <div class="itemvalue"> 1 979.845.5851</div>
        </div>
        <div class="spacer"></div>

        <div class="item">    
          <div class="itemname">Email:</div>
          <div class="itemvalue"><a href="mailto:visit@tamu.edu">visit@tamu.edu</a></div>
          </div>
    </div>

    <div id="connect">
        <div id="socialLinks">
        <a href="https://www.facebook.com/tamu" id="footerFacebook" title="Facebook"><span 
          class="offPage">TAMU Facebook</span></a>
        <a href="http://twitter.com/tamu" id="footerTwitter" title="Twitter"><span class="offPage">TAMU Twitter</span></a> 
        <a href="http://www.youtube.com/tamu" id="footerYoutube" title="YouTube"><span 
          class="offPage">TAMU YouTube</span></a>
        <a href="http://www.flickr.com/photos/aggieland/" id="footerFlickr" title="Flickr"><span 
          class="offPage">TAMU Flickr</span></a>
        <a href="https://foursquare.com/tamu" id="footerFourSquare" title="Foursquare"><span 
          class="offPage">TAMU Foursquare</span></a>
        <a href="http://pinterest.com/tamu/" id="footerPinterest" title="Pinterest"><span 
          class="offPage">TAMU Pinterest</span></a>
        <a href="http://itunes.tamu.edu/" id="footerItunes" title="iTunes"><span class="offPage">TAMU iTunes</span></a>
        </div>
    </div>

    <div id="footerLinks">
      <a href="http://www.tamu.edu/statements/index.html">Site Policies</a><br/>
      <a href="http://visit.tamu.edu//contact-us.html">Contact Us</a><br/>
      <a href="https://compass-ssb.tamu.edu/pls/PROD/bwxkwpro.P_ChooseProspectType">Request Information</a><br/>
      <a href="http://www.tamu.edu/statements/trademark.html">© 2013 All rights reserved</a><br/>
      Texas A&amp;M University
    </div>

    <div class="spacer"></div>
  </div>
  </footer><!--footer ends-->  
  </article>
  </div><!--wrapper ends-->
  <script src="http://dmc-assets.tamu.edu/visit/javascript/plugins.js"></script>
  <script src="http://dmc-assets.tamu.edu/visit/javascript/scripts.js"></script>
 </body>
</html>
